### PR TITLE
Refactor user controller

### PR DESCRIPTION
**Pull request by bcgoss**

### CODE REVIEW

**Comment by bcgoss** [comment]
Close #65

**Comment by bcgoss** [comment]
@j-sm-n @tgisg @MDes41 Ready for review and merge

**Comment by MDes41** [comment]
@bcgoss looks great, noticed you might be able to use find or create method in the initialization of the Twillio service...let me know what you think?

**Comment by bcgoss** [comment]
I don't want to create a record in the database here. I want to find one or create a new active record object. Find_or_create will make a new record, so the longer form is necessary

**Comment by j-sm-n** [comment]
Looks pretty good to me!

**Pull request merged**
